# Generated by Django 4.2.1 on 2023-05-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='post', verbose_name='썸네일 이미지'),
        ),
    ]
